# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-19 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0003_auto_20171119_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
