# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0004_auto_20171119_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
